# Generated by Django 3.2.8 on 2021-10-31 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Ativo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Preço')),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Limite máximo')),
                ('min_limit', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Limite mínimo')),
                ('sleep_time', models.DurationField(verbose_name='Periodicidade de atualização')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ativo',
                'unique_together': {('investor', 'name')},
            },
        ),
    ]
