# Generated by Django 3.2.8 on 2021-10-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='max_limit',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Limite máximo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='min_limit',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Limite mínimo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço'),
        ),
    ]
