# Generated by Django 3.2.8 on 2021-11-04 21:53

import core.facade
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211031_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='max_limit',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[core.facade.validate_negative], verbose_name='Limite máximo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='min_limit',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[core.facade.validate_negative], verbose_name='Limite mínimo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[core.facade.validate_negative], verbose_name='Preço'),
        ),
    ]
